resolver: lts-18.14

packages:
- .

extra-deps:
- github: quanterall/qtility
  commit: fb455c484241c8d65cd5515740c830d2a595bd18
  subdirs:
  - qtility
  # nix-sha256: sha256-V05hNO9ZCJNITNfSqTiODqcWmkDmBm8EouDWr8UT8Yc=

nix:
  enable: false
  packages: 
  - zlib
  - postgresql
