resolver: lts-18.14

packages:
- .

extra-deps:
- github: quanterall/qtility
  commit: 01c4fc42756611da9d3dc04e9ac71ece6ae67268
  subdirs:
  - qtility
  # nix-sha256: sha256-V05hNO9ZCJNITNfSqTiODqcWmkDmBm8EouDWr8UT8Yc=

nix:
  enable: false
  packages: 
  - zlib
  - postgresql
